**Answer to the Question 1**

In [ ]:
class SalesRecord:
    '''Keeps the record of sales 
        Attribute:
            invoicenumber(str): invoice number of the product
            dateofsale(string): date of the sale
            customer(onject)  : Customer who brought the service
            employee(object)  : Employee who sold the service
    '''          
    def __init__(self,invoice,date,customer,employee):
        self.invoicenumber = invoice
        self.dateofsale = date
        self.customer = customer
        self.employee = employee
    
    def __str__(self):
        return f'invoice = {self.invoicenumber} \ndata = {self.dateofsale} \ncustomer = {self.customer} \nemployee = {self.employee}\n'
    
        
        

class Employee:
    ''' Keeps the data of the employee
        
        Attribute:
        nid(str) : NID number of a Employee
        firstname(str): first name of the employee
        lastname(str): last name of the employee
        homephonenumber(str): Home phone number of a employee
    '''
    def __init__(self,nid,fname,lname,hphn):
        self.nid = nid
        self.firstname = fname
        self.lastname = lname
        self.homephonenumber = hphn
    
    def __str__(self):
        return f'Employee:\nnid = {self.nid} \n first name = {self.firstname} \nlast name = {self.lastname} \nHome Phone = {self.homephonenumber}\n'

class Customer:
    '''Keeps the data of the customer

        Attribute:
        firstname(str) : first name of customer
        middlename(str): middle name of the customer
        lastname(str): last name of the customer
        phonenumber(str): phonenumber of the customer
    '''
    def __init__(self,fname,mname, lname, phn, homeaddress):
        self.firstname = fname
        self.middlename = mname if mname != None else None
        self.lname = lname
        self.phn = phn
        self.homeaddress = homeaddress
  
    def __str__(self):
        return f'Customer:\n first name = {self.firstname} \nlast name = {self.lname} \nHome Phone = {self.phn} \nAddress = {self.homeaddress}\n'

class Homeaddress:
    ''' Keep the homeaddress of a customer
        Attribute:
        streetnumber(str): street number of the customer
        postcide(str): postcode of the customer
    '''
    def __init__(self, street, post):
        self.streetnumber = street
        self.postcode = post
    
    def __str__(self):
        return f'Street Number ={self.streetnumber} \npost = {self.postcode}\n'

class Inventory:
    ''' keeps Inventory data

        Attribute:
        product(object list): product object
    '''
    def __init__(self,product):
        self.product = list()
        self.product.append(product)

    def __str__(self):
        String=''
        for i in self.product:
            String.join(i.__str__())
        return String

class Product:
    ''' keep the product info

        Attribut:
        number(str):product number
        name(str) : product name
        price(float) : product price
        quantity(int) : available products
        reparecost(float) : reparing cost of the product
        exchangecost(float) : exchange cost of the product
    '''
    def __init__(self,num, name, price, quantity, repcost, excost):
        self.number = num
        self.name = name
        self.price = float(price)
        self.quantity = int(quantity)
        self.reparecost = float(repcost)
        self.exchangecost = float(excost)
    def __str__(self):
        return f'Product : \nNumber = {self.number} \nName = {self.name} \nPrice = {self.price} \nQuantity = {self.quantity} \n'
    def repare(self):
        print(f'{self.name} will be repared and cost {self.reparecost} ')
    
    def exchange(self,other):
        ''' Args:
        other (object) : is a object of type product
        '''
        print(f'{self.name} will be exchange for {other.name}')


class Application:
    '''Implement the hole system'''
    
    def __init__(self):
        self.salesrecord = None
        self.inventory   = None
    
    def Run(self):
        '''All of this can me made dynamic and fully functional system . but for examination and time constrain i am using static objects.
        
            Dynamic and fucntional: 
                    using, while True : 
                            accessors and mutators

        '''
        
        print("Running the Application :")

        home = Homeaddress('124kalabagan',"1205") 
        c1 = Customer('Sajal','das','dada','01777777',home)
        e1= Employee('Bd09876554','shakib','khan','017890123')
        self.salesrecord = SalesRecord('invoc1312','14-11-2020',c1,e1)
        
        product1= Product("11213","car",134214.123,15,150,1000)
        print(product1)
        
        self.inventory = Inventory(product1)

        print(self.inventory)
        print(self.salesrecord)
 

App= Application()
App.Run()



Running the Application :
Product : 
Number = 11213 
Name = car 
Price = 134214.123 
Quantity = 15 


invoice = invoc1312 
data = 14-11-2020 
customer = Customer:
 first name = Sajal 
last name = dada 
Home Phone = 01777777 
Address = Street Number =124kalabagan 
post = 1205

 
employee = Employee:
nid = Bd09876554 
 first name = shakib 
last name = khan 
Home Phone = 017890123




**Answer to the Question 2**

In [ ]:

class Train:
    def __init__(self , name ,coach):
        self.name = name
        self.coach = coach
        
class Coach:
    def __init__(self,name):
        self.name = name
        self.seatnumber=[True for i in range(25)]



class Ticket:
    def __init__(self,Trains):
        self.Train = Trains

    def booking(self,number,trainChoice):
        booked = list()
        
        for i in self.Train[trainChoice].coach:
            for x,j in enumerate(i.seatnumber):
              if number == 0:
                break
              if  j == True:
                self.Train[trainChoice].coach.seatnumber[x] = False
                booked.append(x)
                number-=1  
        return booked

class creation:

    def create():
        a= Coach('A')
        b= Coach('B')
        c = Coach('C')
        d = Coach('D')
        
        ls=[a,b,c,d]
        tr1=Train('Banalata',ls)
        tr2= Train('Padma',ls)
        t1 = [tr1,tr2]
        ticket = Ticket(t1)
        return ticket


class System:
    def __init__(self,time):
        
        self.creation=creation()
        self.time=None
        if 'pm' in time:
           self.time= int(time[:1])+12
        else:
            self.time=int(time[:1])

        
    def Run(self):
        while True:
            print("system Is running")
            if  8 > self.time < 23:
                Tic=creation.create()
                 
                phone_number=input("Enter Phone Number:")
                trainChoice= int(input("Enter 0 for banalata 1 for padma "))
                number_ofbooking=int(input("Enter Number of booking"))
                seats = Tic.booking(number_ofbooking,trainChoice)
                if len(seats):
                    print("Congratulation! your tickt's re booked")
                    print('Train = ' ,Tic.Train.name)
                    print("coach = ",Tic.Train.coach.name)
                    print("seat Range = ", seat)
                    print('Phone Number = ',phone_number)
                else:
                    print("No seat Available")
            else:
                print("can't buy , time's up")  
                break




system = System('01am')
system.Run()









**Answer to the Question 3**

ans: I do not agree with the above statement. A language is considered fast if it executes fast . so the Speed depends on Execution not interpretation or compilation . But Interpretaion is faster than compilation . So Python might interpret the code faster than Compiling the code. But Execution in python is slow. So Interpretaton of code doesn't make python faster than other language. Because speed depends on execution.

**Answer to the Question 4**

ans: No , i do not agree with the statement. Because while creating a object there should not be any reference to the object. because after creation of a object it will have a reference . But when we see the structure of __init__(self) it takes a reference 'self' as it's first argument. which is a reference to the object that has been created . so the object already created then the reference is assigned and after the assignment we can use and pass the reference self as an argument. So the object is created first then the __init__() is called . 

In [ ]:
#example of Quesion 4


class Check:
    def __init__():
        print("init is called")
        
ch= Check()  

#without the self keyword it will create a type error . that means 
#it always takes a reference. so it can't be called while creation
#of a object

TypeError: ignored

**Answer to the Quesion 5**

ans:Yes we can create a class with out self keyword . because self is a reference to the object which is already created . 

In [ ]:
#example of quesion 5
class Foo:
    pass

obj=Foo()
print(id(obj))

# here id is the place where the object is created in the memeory
# and it returns a value . so we can create a object wihout self

140466792958216


**Asnwer to the question 6**

ans:Yes i agree.

In [ ]:
#1.numpy array is faster then list

#let's check using timeit

import random
import numpy as np

In [ ]:
#for numpy
%timeit rolls_arr= np.random.randint(1,7,6000000)

10 loops, best of 3: 58.2 ms per loop


In [ ]:
#for list
%timeit rolls_list= [random.randrange(1,7) for i in range(0,6000000)]

1 loop, best of 3: 5.7 s per loop


so we can see in above code that numpy is faster

In [ ]:
#2.reshaping : we can reshape ndarray . but cant reshape list

List = [[1,2,3,4],[6,7,8,9]]
print(List)
array=np.array(List)
print("printing array :")
print(array)
array.reshape(4,2)

[[1, 2, 3, 4], [6, 7, 8, 9]]
printing array :
[[1 2 3 4]
 [6 7 8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])